# This file contains values from Cookiecutter

default_context:
  project_name: "finharvest"
  project_description: "A python library to fetch financial data from different sources."
  organization: "Dhanwise"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.7
  github_name: "dhanwise"
  email: "mayanksaraswat333@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
